[package]
name = "dalbrack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
hecs = { version = "0.10.5", features = ["macros"] }
indexmap = "2.9.0"
rand = "0.9.1"
sdl2 = { version = "0.37.0", features = ["image"] }
